### ISSUE TITLE
Incident on package-lock.json formatting

### ISSUE THREAD

**Issue by proxi** [Doist/prettier-config#15]
@rfgamaral Reported incident in https://github.com/Doist/twist-web/pull/2976 where indentation of package-lock.json got lost, resulting in huge diff.

**Comment by proxi** [comment]
@rfgamaral Can you please share the command you used to update `caniuse`? What is your `npm` version?

I still think formatting **should** be 4 spaces (because package.json is). You are right that it is also wrong in todoist-web, I think we never fixed it there after adopting prettier-config, but that doesn't explain the incident.

**Comment by rfgamaral** [comment]
The command used was `npx browserslist@latest --update-db`, not exactly `npm`. I'm assuming it's using `npm` behind the scenes, but it's probably taking some liberties with indentation.

I understand this repo is probably the best place to open this issue, but I don't think there's anything that needs to be changed on our prettier config.

I posted this on the PR, but this can probably be fixed by pining the `caniuse-lite` package in both projects. If we do, dependencies are always installed through `npm`, which formats with 4 spaces, as per this configuration, and we'll never need to rely on `npx browserslist@latest --update-db` again (we'll need to know that version we want to update to, but that's a minor inconvenience).

**Comment by proxi** [comment]
The source of mismatch in todoist-web is that I never reformatted `package-lock.json` in d6f984199eff306a68698a1680d0cdbcf8e05f5b So it is unrelated to this problem.

> The command used was npx browserslist@latest --update-db

I confirmed that this is the source of the problem, running this also breaks indentation for me, and [others reported it](https://github.com/facebook/create-react-app/issues/5817).

@rfgamaral If you think this will again be a problem, we could agree to override formatting for package.json and package-lock.json (it has to be the same). If not, let's keep it at 4 for simplicity.

I will mark a task to clean this up in all repos and add a CI check to make sure we don't break again.

**Comment by proxi** [comment]
CC @Doist/frontend to hear what others think.

**Comment by rfgamaral** [comment]
> If you think this will again be a problem(...)

I don't think so. It's not at all common to use `npx` like that to update a dependency, we always use some form of `npm install...`, and that, as we know, preserves indentation. I have now changed the approach on how we update the `caniuse-lite` database for both `todoist-web` and `twist-web` and this should no longer be a problem.

> (...)we could agree to override formatting for package.json and package-lock.json (it has to be the same). If not, let's keep it at 4 for simplicity.

There's no need, let's keep it at 4. I would simply update `todoist-web`'s `package-json.lock` formatting on `dev` just so everything is consistent and we're all on the same page. And then I believe we can forget about this whole mess 😅

**Comment by proxi** [comment]
Formatting was fixed.
